### ISSUE TITLE
 tws <- twsConnect() just hangs often

### ISSUE THREAD

**Issue by JohannesEmm** [joshuaulrich/IBrokers#28]
### Description

I run Ibrokers with the latest verison of TWS and the API on windows.
While occasionally it connects, in most cases just hangs after  tws <- twsConnect() (Port, host, client id etc. are all default values, and moreover it works every 10th time or so). Even with timeout set or verbose, no output is shown, no log file create in thh TWS folder.
Also, is there a rule if you should start TWS before or after R?
But in either case, only works randomly for me.

### Expected behavior

[Describe the behavior/output you expected]

### Minimal, reproducible example

```r
 tws <- twsConnect()
```

### Session Info

```r
[Insert your sessionInfo() output]
```

**Comment by RudyMartin** [comment]
How is the timeout set for the connection?

**Comment by JohannesEmm** [comment]
yeh thought this hsould fix it but timeout doesn change behavior at all
`tws <- twsConnect(verbose = T, timeout = 1)`

also hangs indefinitively.

**Comment by joshuaulrich** [comment]
I'm not able to replicate this on my machines. I doubt it is something specific to the IBrokers package.

It would help to have your `sessionInfo()` output. That would give more information about your OS and environment.

One idea to try: turn off any firewalls you have running. And/or see if there's a way to trust all local connections. It might be an issue with your computer's internet settings.

**Comment by JohannesEmm** [comment]
well this could be it due to an ad blocker!
Thanks!
